### ISSUE TITLE
Question about "first-class" lenses

### ISSUE THREAD

**Issue by menelaos** [5outh/nanoscope#64]
I have a use case where I want to expose getters from a module but the actual object I want to focus on is provided later.

I.e., I need to pass around lenses as values without constructing `nanoscope(objectIDontHaveAccessToRightNow)`

It seems that this used to be the "normal" way up until https://github.com/5outh/nanoscope/issues/11.

As `nanoscope` exposes the individual lenses, that approach is still possible:

```javascript
const abLens = new nanoscope.PathLens(["a", "b"]);
const cdLens = new nanoscope.PathLens(["c", "d"]);
const abcdLens = abLens.compose(cdLens);

// Somewhere else
abcdLens.view(objectIJustGotAccessTo).get()
```

Since I couldn't find a mention about this in the docs,
I figured that this API might not be considered "stable".

Should I avoid constructing lenses directly?

**Comment by 5outh** [comment]
I removed the direct constructors from the docs just because I thought people would prefer the other way of doing things. You can still use them; I actually have been meaning to put the docs back up because there was another ticket mentioning the same thing. Feel free to use them, and thanks for your interest!

**Comment by menelaos** [comment]
Great!
